### PR TITLE
Seperate retirement accounts from brokerage accounts

### PR DESCRIPTION
**Pull request by andreva7**
Not fixed:  stock history does not work unless you manually create the "stockquotes" directory manually.

### CODE REVIEW

**Comment by andreva7** [comment]
Add retirement accounts

**Comment by andreva7** [comment]
Let you guys play around with this change.  
Want your feedback on the updates to the portfolio report.

I have not validated "download" with the new account type, so there is probably bugs there.

**Comment by clovett** [comment]
Fixed now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andreva7** [comment]
Awesome!

-Andre

________________________________

**Pull request merged**
