### PR TITLE
Merge pull request #18 from clovett/master

### PR DESCRIPTION
**Pull request by andreva7**
clovett -> andreva7

### CODE REVIEW

**Comment by andreva7** [comment]
merge

**Comment by lovettchris** [comment]
Yeah, weird, I didn't see any "Files changes", so it was a noop ?

**Comment by andreva7** [comment]
It’s me being confused after not having done this in 1 year. I was just trying to pull your changes in my branch.

BTW, the current bug I see is, if I have multiple accounts with one bank and then select synchronize account, the OFX call passes both accounts.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lovettchris** [comment]
Ah, yes, I see synchronize account synchronizes the "online account" associated with the selected account, so yes, if you have multiple accounts associated with that online institution then it will download them all.  Why is this a problem?

**Comment by andreva7** [comment]
The second account is not working. Not sure if it’s a configuration problem or a bug at this point. Having the synchronize account just target that one account would make the troubleshooting easier.

-Andre

**Pull request closed without merging**
